services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: blimlist-db
    environment:
      - POSTGRES_DB=blimlist
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço do Backend
  api:
    build: ./backend
    container_name: blimlist-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/blimlist

volumes:
  postgres_data: