spring.application.name=backend

# Porta do Servidor
server.port=8080

# Configuração do PostgreSQL
# O host 'db' é o nome que daremos ao serviço no Docker Compose
spring.datasource.url=jdbc:postgresql://db:5432/blimlist
spring.datasource.username=postgres
spring.datasource.password=blim123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
